### ISSUE TITLE
regarding the crates.io name

### ISSUE THREAD

**Issue by RayMarch** [SichangHe/shame.rs#2]
Hi, 
I noticed you own the `shame` crate on crates.io. I've been wanting to use that name for a project I've been working on for some years now, and that is ready for release soon. The project is https://github.com/raymarch/shame, a shader-metaprogramming DSL for webgpu/vulkan.
How strongly do you feel attached to this particular name for your crate?
would you be open to transferring the `shame` name to us? It would mean a lot to me.

Is there some way I can message you privately about this?

**Comment by SichangHe** [comment]
Yes, please contact me by email.

**Comment by RayMarch** [comment]
Where can i find your email address?
